### ISSUE TITLE
Can not see the "Profile" icon in Edge Inprivate mode.

### ISSUE THREAD

**Issue by RichardSunMS** [MicrosoftDocs/Edge-Enterprise#212] opened 2021-07-28 03:36 UTC
Hi I am having the Conditional Access issue in Edge Inprivate mode with error message: 
![image](https://user-images.githubusercontent.com/11748089/127259525-8c72b57a-c39e-49e4-a8e2-3fda36499e27.png)

I am following this doc, but can't find the profile icon as this page described. 
Can you help?
![image](https://user-images.githubusercontent.com/11748089/127259656-c4323023-113d-456a-8bc1-159b65085594.png)

Thanks.
Richard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c87844-d7d4-22ff-92dc-49cea06e2e85
* Version Independent ID: 909054ee-53da-8d02-8347-57aeb1d96f32
* Content: [Microsoft Edge and Conditional Access](https://docs.microsoft.com/en-us/deployedge/ms-edge-security-conditional-access#see-also)
* Content Source: [edgeenterprise/ms-edge-security-conditional-access.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/ms-edge-security-conditional-access.md)
* Product: **microsoft-edge**
* GitHub Login: @srugh
* Microsoft Alias: **srugh**

**Comment by Y-Kelly** [comment] 2021-07-28 20:17
@RichardSunMS Hi!  I believe you cannot see your profile while InPrivate.  Does it work as expected in a normal MS Edge window?

**Comment by RAJU2529** [comment] 2021-08-01 03:06
@RichardSunMS . Only Profile cane be view and fully accessible in normal mode only. Also in private mode,  profile cannot be  view by all users. This restriction is by default or by design.

**Comment by RichardSunMS** [comment] 2021-08-02 08:55
@Y-Kelly , sorry for the late response. 
@Y-Kelly , @RAJU2529 . Edge Normal mode works fine for us. In Chrome, incognito mode, I installed a windows 10 accounts extension and successfully work around this issue.

I think this conditional access policy should be applied recently. So now our problem is can't sign in customers if they use InPrivate mode of Edge, but Chrome can with the extension. 

What is your suggest on Edge in-private mode?

**Comment by RAJU2529** [comment] 2021-08-02 11:18
@RichardSunMS , If chrome is can, but not on edge, that means, in your organization, chrome enterprise browser is deployed with his associated admx templates and configured through GPO?

**Comment by RichardSunMS** [comment] 2021-08-03 01:47
@RAJU2529 , what is GPO? I am using Chrome version: Version 92.0.4515.107 (Official Build) (64-bit) and here is the extension I installed for Chrome: chrome://extensions/?id=ppnbnpeolgkicgegkbkbjmhlideopiji
Try the login in https://www.office.com in Edge Inprivate mode, it will fail, but it can succeed for https://www.outlook.com. Any specific reason?

**Comment by RAJU2529** [comment] 2021-08-03 04:29
@RichardSunMS I will try afternoon.

**Comment by Y-Kelly** [comment] 2021-08-05 20:39
@RichardSunMS Since we've connected offline, closing this issue.

**Closed by Y-Kelly** 2021-08-05 20:39 UTC
