### ISSUE TITLE
Bad links on page 

### ISSUE THREAD

**Issue by KevinNSTA** [MicrosoftDocs/Edge-Enterprise#183] opened 2021-06-23 00:22 UTC
Some links on the page are bad - looks like it's accidentally doubled from a bad relative link- `/deployedge/deployedge/`

 - "Configure Microsoft Edge policy settings on Windows" and links to https://docs.microsoft.com/en-us/deployedge/DeployEdge/configure-microsoft-edge 
 - another is "Configure for Windows with Mobile Device Management" aimed at https://docs.microsoft.com/en-us/deployedge/deployedge/configure-edge-with-mdm 
 - "Configure for macOS using a .plist" aimed at https://docs.microsoft.com/en-us/deployedge/deployedge/configure-microsoft-edge-on-mac 
 - Configure for macOS with Jamf - https://docs.microsoft.com/en-us/deployedge/deployedge/configure-microsoft-edge-on-mac-jamf 
 - Configure for Windows with Intune - https://docs.microsoft.com/en-us/deployedge/mem/intune/configuration/administrative-templates-configure-edge?bc=https%3a%2f%2fdocs.microsoft.com%2fDeployEdge%2fbreadcrumb%2ftoc.json&toc=https%3a%2f%2fdocs.microsoft.com%2fDeployEdge%2ftoc.json

Really, all of these are aiming at relative links, like `./deployedge/configure-edge-with-mdm` and are just a smidge off 

Also - one line seems to link back to the same page you are already on? 
> [Manage Microsoft Edge extensions in the enterprise](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions). Create a strategy to manage extensions and set up administrative templates required for managing the browser.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf796fac-09b2-f205-62d8-69ca77f9743e
* Version Independent ID: 60767e14-08a8-f3d1-0d34-2384b739bc1f
* Content: [Manage Microsoft Edge extensions in the enterprise](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions)
* Content Source: [edgeenterprise/microsoft-edge-manage-extensions.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-manage-extensions.md)
* Product: **microsoft-edge**
* GitHub Login: @AndreaLBarr
* Microsoft Alias: **aspoddar**

**Comment by Y-Kelly** [comment] 2021-06-29 20:12
@KevinNSTA Hi!  Just to confirm, are the broken links in this (https://docs.microsoft.com/en-us/deployedge/microsoft-edge-manage-extensions#before-you-begin) section of the document?  

![image](https://user-images.githubusercontent.com/74324031/123861052-92f68900-d8db-11eb-918b-ca480cfbda7a.png)

I'm not able to reproduce and just wanted to double check I'm looking at the right area.  Thanks!

**Comment by PsychoData** [comment] 2021-06-29 20:18
@Y-Kelly  looks like someone already fixed it 
https://github.com/MicrosoftDocs/Edge-Enterprise/commit/6d609b1ca6c4b9c5403daa3f46de2a79cdd2a846#diff-938d0bcfc4638dd17e97126b17591444fe302fcd8e24ade93a12caa0251824db

**Comment by Y-Kelly** [comment] 2021-06-29 20:19
Great!  I'll close this issue.  Thanks!

**Closed by Y-Kelly** 2021-06-29 20:19 UTC

**Comment by PsychoData** [comment] 2021-06-29 20:23
oh - it does seem like the link mentioning "Manage Microsoft Edge extensions in the enterprise" still links back to the same page you are already on though 
![image](https://user-images.githubusercontent.com/3719116/123862411-51270c00-d8f6-11eb-99d3-4c1b86fe7ca8.png)
