### ISSUE TITLE
Missing 106 stable in catalog and WSUS

### ISSUE THREAD

**Issue by CanastraRF** [MicrosoftDocs/Edge-Enterprise#416] opened 2022-10-04 07:00 UTC
Hi

the new release 106 of edge is in update catalog und WSUS not available.
Only edge extended and webview2 is updated to 106.
Please deploy all versions to catalog and wsus after release.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ffcaf54-ce86-1b30-e947-540bf07a54c3
* Version Independent ID: 81267e97-e284-ff00-b081-476934538326
* Content: [Microsoft Edge release notes for Stable Channel](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel)
* Content Source: [edgeenterprise/microsoft-edge-relnote-stable-channel.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-relnote-stable-channel.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **leahtu**

**Comment by Y-Kelly** [comment] 2022-10-04 17:46
Closing as this appears to be a duplicate of previous issue.

**Closed by Y-Kelly** 2022-10-04 17:46 UTC
