### ISSUE TITLE
Hide first-run-experience prevents auto-import of passwords

### ISSUE THREAD

**Issue by dsolodow** [MicrosoftDocs/Edge-Enterprise#193] opened 2021-07-07 15:24 UTC
Passwords not imported automatically when first run experience hidden. Per my support case, this is by design but is not publicly documented/posted anywhere. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#autoimportatfirstrun)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment] 2021-07-12 21:54
@dsolodow Hello!  Just to confirm, you've configured both the HideFirstRunExperience and AutoImportAtFirstRun policies and specifically the passwords are not being imported?  

Are you still working with support?  I do see our engineers are working on a fix for something similar but not sure if it is your exact case.  Thanks!

**Comment by dsolodow** [comment] 2021-07-12 22:49
Correct, I've configured both of those and no password import. Still working with support.
They sent me a workaround that _looks_ to work:
Create
"%LOCALAPPDATA%\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\AC\MicrosoftEdge\User\Default"
and then launch Edge for the FRU

**Comment by Y-Kelly** [comment] 2021-07-19 19:41
@dsolodow Hi!  It looks like the fix I saw was released to Canary Version 93.0.951.0+.  Do you know if this new build resolves your issue?

**Comment by dsolodow** [comment] 2021-07-19 19:57
I haven't had a chance to test; this is the first I've heard of a build
with the fix.

**Comment by Y-Kelly** [comment] 2021-07-28 20:30
@dsolodow Just to follow up, have you had any updates from MS Support?  Is your issue still reproducing?  Thanks!

**Comment by dsolodow** [comment] 2021-07-28 20:36
Confirmed fixed in 92.0.902.55 and higher

**Comment by Y-Kelly** [comment] 2021-07-28 20:38
@dsolodow Thanks!  Closing this issue.

**Closed by Y-Kelly** 2021-07-28 20:38 UTC
