### ISSUE TITLE
ExemptFileTypeDownloadWarnings description incorrect

### ISSUE THREAD

**Issue by cjg88** [MicrosoftDocs/Edge-Enterprise#411] opened 2022-09-15 23:22 UTC
The first examples in the description show that the json string should define the file_extension and then the domains but then the examples below that show it should be the domains then the file_extension. 

This setting does not work if using the former. It will only work when defined with domains first then file_extension. 

i.e.

[ { "file_extension": "eml", "domains": ["*"] } ] - this does not work.

[ { "domains": ["*"], "file_extension": "eml" } ] - this does work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 198c6f64-9e5c-f18e-8439-8d0d11d4228d
* Version Independent ID: 83f32be1-063c-284c-dfdc-6b5976a5b7cc
* Content: [Microsoft Edge Browser Policy Documentation](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies)
* Content Source: [edgeenterprise/microsoft-edge-policies.md](https://github.com/MicrosoftDocs/Edge-Enterprise/blob/public/edgeenterprise/microsoft-edge-policies.md)
* Product: **microsoft-edge**
* GitHub Login: @dan-wesley
* Microsoft Alias: **stmoody**

**Comment by Y-Kelly** [comment] 2022-09-19 19:04
@cjg88 Thanks for the feedback.  I've reached out to the team about the incorrect examples in the policy documentation.  I can follow up with any updates from them.

**Comment by Y-Kelly** [comment] 2022-09-19 21:31
@cjg88 The team has tested both cases and was able to successfully set up the policy in either order.  

Can you provide more information about the issue you are experiencing and what happens when it "does not work"?  Also, can you include a screenshot of how the policy is displayed in edge://policy?  Thanks!

**Comment by Y-Kelly** [comment] 2022-10-10 20:39
Closing as it has been a few weeks with no reply.  Team has tested scenario and cannot reproduce.

**Closed by Y-Kelly** 2022-10-10 20:39 UTC
