### ISSUE TITLE
Edge 111, Sidebar appearing despite GPO to disable

### ISSUE THREAD

**Issue by AndyH16** [MicrosoftDocs/Edge-Enterprise#491] opened 2023-03-14 12:07 UTC
As above, we have the GPO 'Show Hubs Sidebar' set to Disable but as of 111.0.1661.41 (which mentions a new Sidebar), we now have the Sidebar appearing. Should the latest ADMX cover this new Sidebar?

Looking in the settings within Edge, the enabled setting is greyed out, with 'Always Enabled' switched on.

**Comment by Y-Kelly** [comment] 2023-03-14 18:31
@AndyH16 I've checked with the team and they mentioned if you HubsSidebarEnabled set to Disabled previously, you may have to re-disable it.  Basically if you had the sidebar disabled before, this change in v111 may have enabled it.  

If you are still having issues after re-disabling, please reach out and send a screenshot of your edge://policy/ page, please remove any PII information.  Thanks!

**Comment by Y-Kelly** [comment] 2023-03-15 17:27
@AndyH16 Hi!  Just to clarify, did the behavior change since v111 was released to Stable?  Prior it was working as expected?  

Are you trying to set the policy to recommended?  For example, disable via policy but you would like users to have the ability to turn it on if they chose?  

It would be great if you had some screenshots so our developers can try and reproduce.  Thanks!

**Comment by AndyH16** [comment] 2023-03-16 08:55
The behaviour changed when v111 was released. We had it set to disabled but within the 'user can override' section. I can't say that I tested whether the option to enable it as a user was working though, as I personally had no need to use the sidebar.

Ideally, yes, we would like to have it set so that it was disabled by default but users could enable if they wished. (recommended setting)

**Comment by zakx** [comment] 2023-03-16 17:09
Same on macOS. It's really annoying how Microsoft manages to make Edge worse with every iteration.

**Comment by holow29** [comment] 2023-03-16 22:13
Tested on MacOS 111.0.1661.44 and 113.0.1741.0 fresh installs. Policy appears to have no effect even though it shows up properly in edge://policy just as above.

**Comment by Y-Kelly** [comment] 2023-03-16 23:18
Hi Everyone - I've spoken to the team and in Microsoft Edge v111, if the HubsSidebarEnabled policy is set as disabled with Recommended level, the settings page shows gray out where users can not toggle on to show sidebar (this is **same** as previous Microsoft Edge version), users can still get back sidebar by hover/click the Bing icon in the toolbar. 

If Admin disabled HubsSidebarEnabled policy with Mandatory level, both sidebar and the Bing icon in the toolbar will be invisible (users cannot get back sidebar).

**Comment by holow29** [comment] 2023-03-16 23:38
@Y-Kelly Thank you for looking into this. I don't see the behavior you have described documented in either the [policy page](https://learn.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#hubssidebarenabled) or the specific [page dedicated the the sidebar policies](https://learn.microsoft.com/en-us/DeployEdge/microsoft-edge-sidebar).

Additionally - where does this leave MacOS admins? As far as I know, there is no way to make a policy mandatory on MacOS. The policy page says it will disable the sidebar on both Windows and MacOS, but there is no way to do that currently on MacOS.

**Comment by holow29** [comment] 2023-03-17 00:27
@Y-Kelly Thank you for looking into this. I don't see the behavior you have described documented in either the [policy page](https://learn.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#hubssidebarenabled) or the specific [page dedicated the the sidebar policies](https://learn.microsoft.com/en-us/DeployEdge/microsoft-edge-sidebar), so I would suggest changes to those pages.

If I set the policy as mandatory on MacOS, I get the behavior you describe, so that appears to be working.

**Comment by zakx** [comment] 2023-03-17 17:51
How do you set the policy to mandatory on macOS?

**Comment by holow29** [comment] 2023-03-17 17:56
@zakx com.microsoft.Edge.plist must be in /Library/Managed Preferences/ for Mandatory level. For Recommended Level, default ~/Library/Preferences is used.

**Comment by zakx** [comment] 2023-03-17 17:59
Thanks, that works and removes the horrible sidebar.

**Comment by Y-Kelly** [comment] 2023-03-21 17:19
Closing this bug as it appears issue has been resolved.  

FYI, there are additional improvements for sidebar shipping with 112.   More information in the Release Notes: https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-beta-channel#version-1120172211-march-17-2023

**Closed by Y-Kelly** 2023-03-21 17:19 UTC

**Comment by holow29** [comment] 2023-03-21 17:44
@Y-Kelly Is there another issue to fix the documentation? If not, this issue should probably stay open because, as it is now, the documentation says the policy can be either recommended or mandatory. However, the description (https://learn.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#hubssidebarenabled) only specifies the behavior of mandatory without making reference to it as such.
